### ISSUE TITLE
batch 

### ISSUE THREAD

**Issue by b1lake** [kharchenkolab/pagoda2#119] opened 2021-02-19 23:17 UTC
Hi, when including a batch factor when creating a new pagoda2 object I am now getting the following error:

p2 <- Pagoda2$new(x = countMatrix, trim=10, batch = countMatrix.batch)
Error in initialize(...) : unused argument (batch = countMatrix.batch)

Any way to rectify this?

Thanks!

Blue

**Comment by evanbiederstedt** [comment] 2021-02-19 23:45
Hi @b1lake 

Thanks for the issue. 

This is interesting! It didn't occur to me previously that users would initialize Pagoda2 objects with the `batch` param. 

Currently, the following code should work:

```
p2 <- Pagoda2$new(x = countMatrix, trim=10)
p2$batch <- countMatrix.batch
```

Please let me know if that works.

Given you say you are now receiving this error, I'm happy to revert to the behavior whereby you can do:

```
p2 <- Pagoda2$new(x = countMatrix, trim=10, batch = countMatrix.batch)
```

**Comment by evanbiederstedt** [comment] 2021-02-20 00:09
Hello @b1lake 

I think the issue is now fixed---this is my error; I didn't notice that people would set `batch` via the Pagoda2 constructor. Thanks for pointing this out :)

Try installing pagoda2 via the following:

```
git clone https://github.com/kharchenkolab/pagoda2.git
cd pagoda2
git checkout devel
git pull origin devel --force
R CMD BUILD .
R CMD INSTALL *gz
```

Then this should work:
```
p2 <- Pagoda2$new(x = countMatrix, trim=10, batch = countMatrix.batch)
```

Please let me know. If it works, we'll push to the main branch. There are several updates to make since publishing on CRAN.

Thanks, Evan

**Comment by evanbiederstedt** [comment] 2021-02-20 21:31
Fix should be on the main branch now as well

**Comment by b1lake** [comment] 2021-02-22 19:54
Great! This works, thank you for fixing this so quickly!

**Comment by evanbiederstedt** [comment] 2021-02-22 20:07
That's great to hear! Thanks again

Best, Evan

**Closed by evanbiederstedt** 2021-02-22 20:07 UTC
Labels: bug
