### ISSUE TITLE
testPathwayOverdispersion returns NA

### ISSUE THREAD

**Issue by duocang** [kharchenkolab/pagoda2#126] opened 2021-09-30 18:17 UTC
Hi.

I don’t really know why `testPathwayOverdispersion` returns a score of pathway is `NA`.

```
> score[1:4, 1:4]
   AAACCCAAGCTGTTCA_8 AAACCCAAGGCGAACT_8 AAACCCAGTGAGACCA_8 AAACCCAGTGCGTGCT_8
P1                 NA                 NA                 NA                 NA
P2          -0.2931884         -0.2896116         -0.3545110         -0.2964433
P3         -0.4599188         -0.4599188         -0.4599188         -0.1599542
P4          -0.1952260         -0.2375788         -0.2264670         -0.0812107
```

I have no clue what does `if (avar>0.5)` mean.

```
pwpca <- papply(gsl, function(sn) {
          lab <- proper.gene.names %in% get(sn, envir = setenv)
          if (sum(lab)<1) { 
            return(NULL)
          }
          pcs <- irlba(x[,lab], nv=nPcs, nu=0, center=cm[lab])
          pcs$d <- pcs$d/sqrt(nrow(x))
          pcs$rotation <- pcs$v
          pcs$v <- NULL

          # get standard deviations for the random samples
          ngenes <- sum(lab)
          z <- do.call(rbind,lapply(seq_len(n.randomizations), function(i) {
            si <- sample(ncol(x), ngenes)
            pcs <- irlba(x[,si], nv=nPcs, nu=0, center=cm[si])$d
          }))
          z <- z/sqrt(nrow(x))

          # local normalization of each component relative to sampled PC1 sd
          avar <- pmax(0, (pcs$d^2-mean(z[, 1]^2))/sd(z[, 1]^2))

          if (avar>0.5) {
            # flip orientations to roughly correspond with the means
            pcs$scores <- as.matrix(t(x[,lab] %*% pcs$rotation) - as.numeric((cm[lab] %*% pcs$rotation)))
            cs <- unlist(lapply(seq_len(nrow(pcs$scores)), function(i) sign(cor(pcs$scores[i,], colMeans(t(x[, lab, drop = FALSE])*abs(pcs$rotation[, i]))))))
            pcs$scores <- pcs$scores*cs
```

**Comment by evanbiederstedt** [comment] 2021-09-30 18:45
Hi @duocang 

Thanks for using pagoda2

Could you give me a reproducible example so I could look into this issue? At the moment, it's not clear at all how I could debug this. 

RE: avar

This particular bit of code was originally applied in SCDE: https://github.com/hms-dbmi/scde/blob/master/R/functions.R#L1969-L1974

@pkharchenko could offer more details as to why there's a 0.5 cutoff

Thanks, Evan

**Comment by duocang** [comment] 2021-09-30 19:54
@evanbiederstedt 





Hi.

Please try the data and code in Onedrive.

https://1drv.ms/u/s!AtjLM4-mbBLkx9UVNeDXs1DvDB8vXg?e=4NF4Xl

```R
library(pagoda2)


read_counts <- readRDS("read_counts.rds")
genes_list <- readRDS("genes_list.rds")

p2 = Pagoda2$new(read_counts, n.cores = 1,log.scale=T)
p2$adjustVariance(plot=F)
p2$calculatePcaReduction(nPcs = 50, use.odgenes=F,fastpath=F)

env = list2env(genes_list)

p2$testPathwayOverdispersion(setenv = env, verbose = T, recalculate.pca = T,
                             plot = T, min.pathway.size = 3)

path_names = names(genes_list)
score = matrix(NA,nrow=length(path_names),ncol=ncol(read_counts))
rownames(score) = path_names
colnames(score) = colnames(read_counts)

for(i in 1:length(p2$misc$pwpca)){
  if(!is.null(p2$misc$pwpca[[i]]$xp$score)){
    score[i,] = as.numeric(p2$misc$pwpca[[i]]$xp$scores)
  }
}

```

**Comment by duocang** [comment] 2021-10-01 09:03
@evanbiederstedt @pkharchenko 

Hi. One more question:
How do I interpret the score matrix?

Four pathways
```R
 Cell              Astrocyte_Cahoy (2137g) Astrocyte_Lein (34g) Microglia_lavin (603g) Oligodendrocyte_Cahoy (1751g)
1772071015_C02               -4.045455            -1.622229              -1.995894             8.212579
1772071017_G12               -4.539054            -1.582736              -2.394188             8.551861 
1772071017_A05               -3.391540            -1.710547              -2.467557             9.629696  
1772071014_B06               -3.623061            -1.524846              -2.424839            11.129122 
1772067065_H06               -4.291317            -1.811003              -2.852107            13.265595  
1772071017_E02               -3.564566            -1.565542              -2.736552            12.819157      
```

Should I compare the value **row-wise** or **column-wise**?



- For row-wise, I select a pathway from four for/in a cell. Then every cell can have a possible pathway.
- For column-wise, I select top cells from one pathway. Then one cell can be top in more than one pathway (I do not think this is a problem).



I personally take the column-wise and get top cells which I considered to be **this-pathway-enriched** cells .

`AUCell` takes column-wise selection by modifying `AUC` threshold..

> Plotting the AUC histogram of a specific gene set, and setting a new threshold:

```R
geneSetName <- rownames(cells_AUC)[grep("Oligodendrocyte_Cahoy", rownames(cells_AUC))]
AUCell_plotHist(cells_AUC[geneSetName,], aucThr=0.25)
abline(v=0.25)
```


![image](https://user-images.githubusercontent.com/14146871/135594002-0cdf5067-6c54-4bae-a341-2dc30a14bd6f.png)




Maybe you can help me clarify it is to select a pathway for a cell or to select top cells from a pathway.

**Comment by evanbiederstedt** [comment] 2021-10-02 00:08
Hi @duocang 

So, I think you see the code in question is here: https://github.com/kharchenkolab/pagoda2/blob/master/R/Pagoda2.R#L1956-L2197

The "score" calculation is here: https://github.com/kharchenkolab/pagoda2/blob/master/R/Pagoda2.R#L2020-L2049

For your data, if you take a look here: `p2$misc$pwpca[[1]]$xp`, there is no score for the first pathway:

```
> names(p2$misc$pwpca[[1]]$xp)
[1] "d"        "u"        "iter"     "mprod"    "rotation"
```

As you've gathered, that's because of the conditional above with `avar > 0.5`. 

If you check the original function in SCDE, that conditional didn't exist: https://github.com/hms-dbmi/scde/blob/master/R/functions.R#L1865-L1975

I suspect that `avar` was a heuristic Peter used to find significant pathways, but @pkharchenko will have to chime in. 

Given it's a heuristic, feel free to remove that conditional to get a score. 

In terms of the big picture, I would recommend you use `getHierarchicalDiffExpressionAspects()` instead. I think the pathway analysis using PCA from SCDE served its purpose several years ago with the assumptions of ~1K cells and GO pathways, but the procedure is a bit crude. Based on the data you've given, I'm not really sure what your "pathways" are....so I would take this analysis with a grain of salt. I realize why bioinformaticians liked this approach, but I don't think you should be using this for robust biological inferences.

@pkharchenko might add some comments regarding more details, but based on my comments above, I think it's best to close this issue.

**Closed** 2021-10-02 00:09 UTC
