### ISSUE TITLE
Web browser kills pagoda2WebApp when doing DE on large datasets

### ISSUE THREAD

**Issue by GMaciag** [kharchenkolab/pagoda2#88] opened 2019-07-08 08:50 UTC
I'm working on a large dataset of over 30k cells. After serializing it to a bin file, I want to be able to do differential expression analysis between celltypes using the pagoda2 web app. Everything works fine when doing DE on a smaller number of cells. However, if I try to run DE between selections of cells that total over 8k cells, the website crashes - the web browser kills the page ("Something went wrong when displaying this web page"). It usually happens when the progress reaches 50% (when it says calculating instead of percentage). I'm using Chrome on Mac OS. 

I think the problem is that the calculations with so many cells take long enough for Chrome to decide to kill the page as unresponsive. Because this cannot be altered in Chrome, I tried Firefox. In Firefox you can edit the parameters through the about:config page. Specifically, I tried altering the `network.http.connection` and `browser.cache.disk` parameters (and other similar ones). I couldn't find a combination of parameter changes that would solve the issue permanently - I managed to run DE on over 8k cells once or twice, but then the web page would keep crashing after that (memory issues, I suspect).

Did anyone encountered similar problem or has an idea for a solution? Or maybe, what combination of parameters in Firefox I should try? I don't know exactly how pagoda2 processes the data with the web app, so it's hard for me to guess what exactly could be the root of this issue. Any tips will be appreciated!

**Comment by GMaciag** [comment] 2019-07-08 11:50
So, I have found the solution to the problem myself. I'll post it here, in case anyone else encounters similar issue. 

As far as I know, this fix works only on firefox, since Chrome doesn't allow for altering its parameters in the same way.  In Firefox, you need to change the following settings on the `about:config` page:
`browser.tabs.remote.autostart = false`
`browser.tabs.remote.autostart.2 = false`
The default values of that parameters are `true`. Some versions of firefox only have the first parameter. 

That's basically it! After a restart, the browser should keep the web page open no matter how long it takes to process a file. You may get a popup asking whether to "kill a script that stop working", simply select "wait" on that one. 

As single cell datasets become bigger and bigger, more and more people may have this problem. Maybe it would be beneficial to include this information in the official tutorial for pagoda?

**Comment by barkasn** [comment] 2019-07-08 16:22
Hi @GMaciag thank you for pointing this out. The reason this happens is that around 50%, once the download has completed and the differential expression analysis is about to start there is a memory inefficient matrix transformation. This was a very rare, but as datasets get larger its becoming more and more of an issue. Certainly something to fix.

**Comment by barkasn** [comment] 2020-07-13 22:14
@evanbiederstedt This is an issue on the web front end, there is a transformation from row to column sparse matrix (or vice versa) that goes through a full matrix and is very inefficient. A fix for this would be to find an algorithm that can do this efficiently (most likely through triplet representation) and replace it. If memory serves the issue is here: 

https://github.com/kharchenkolab/pagoda2/blob/232390fd9268a45be85d5236af3e5c91d5713c87/inst/rookServerDocs/js/dataController.js#L205

**Comment by evanbiederstedt** [comment] 2021-02-28 04:59
Haven't run into this issue yet. I may close, as I don't think we have a great solution on the horizon in the short-term.

**Closed by evanbiederstedt** 2021-02-28 04:59 UTC
Labels: help wanted
